CREATE TABLE T_AUTHORITY (
 AUTHORITY_ID CHAR(4) NOT NULL PRIMARY KEY,
 AUTHORITY_NAME VARCHAR(16) NOT NULL,
 AUTHORITY_TITLE VARCHAR(16),
 DESCRIPTION VARCHAR(64)
);


CREATE TABLE T_RESOURCE (
 RESOURCE_ID CHAR(8) NOT NULL PRIMARY KEY,
 URL VARCHAR(128),
 AUTHORITY  VARCHAR(16)
);

CREATE TABLE T_ROLE (
 ROLE_ID CHAR(4) NOT NULL PRIMARY KEY,
 ROLE_NAME VARCHAR(16) NOT NULL,
 TYPE VARCHAR(16) NOT NULL
);


CREATE TABLE `t_user` (
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(16) DEFAULT NULL,
  `PASSWORD` varchar(64) DEFAULT NULL,
  `TYPE` varchar(16) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8


INSERT INTO t_authority (AUTHORITY_ID, AUTHORITY_NAME, AUTHORITY_TITLE, DESCRIPTION) VALUES ('0001', 'user_create','用户创建', '');
INSERT INTO t_authority (AUTHORITY_ID, AUTHORITY_NAME, AUTHORITY_TITLE, DESCRIPTION) VALUES ('0002', 'user_list','用户列表', '');